[[signers]]
name = "rficu"
email = "rficu@email.com"
key = "3c2PgNisX4vOumXAYVETS1aDKLHYEuhKSo7i1xnwr2Y="
signature = "+Bl5DtPMfKsxKd4eNQybgpbcrF70TuyMfp3Eyu8xQ1CWkBrhDEcx0jUO084EMZ7dbVw/v+0x0MMkbX/gZlGvBQ=="
