author_name = "rficu"
author_email = "rficu@gmail.com"

[[packages]]
	name = "gcc"
	version = "10.0.2"
	path = "/usr/bin/gcc"
	sha256 = "4ce09730ea4670375f4179994ef637c249ec06c4abd835a7b98b311e3b529c89"

[[packages]]
	name = "x265"
	version = "0.161.3011 cde9a93"
	path = "/usr/bin/x265"
	sha256 = "a9794bb93b5742cdaae819323f46997086f74c09e3a27229d74c3f8fc1950ea9"
