[[packages]]
	name = "gcc"
	version = "10.0.2"
	sha256 = "4ce09730ea4670375f4179994ef637c249ec06c4abd835a7b98b311e3b529c89"
	ipfs = "QmdJpG7iQ4hahTtC5CuBavUzqeWvfq4KArzayygwezbaSW"
	signature = "SufsB52XAt5snSxb/m3oAPp3kCOykVapQgQtUVLKuwrxOfx14Hc37H8LCBm8xKnHUvybyR2p6bcLbZpKa4alDQ=="

[[packages]]
	name = "x264"
	version = "0.160.3011 cde9a93"
	sha256 = "40cddc5f4aabf5994c42e852088209dc644e0b6a751bfb43cb2c5c182366ffee"
	ipfs = "QmUXHuWFdKDb5Jp3S7ZXNg766du8N938oF186yJuSx7EcV"
	signature = "lmv+n7CFnkZQuQ75Vn1S2R55+BxJr4YmuMH76MzKjCtUlC3ydgybfMwaYTQ8mRroyHmOo56uR41Aqa3lkTLICg=="

[[packages]]
	name = "x265"
	version = "0.160.3011 cde9a93"
	sha256 = "a9794bb93b5742cdaae819323f46997086f74c09e3a27229d74c3f8fc1950ea9"
	ipfs = "Qma4g2bCUeBPkU8Rvfq1Nvm7V96NViLyD555QEEQx9AFG1"
	signature = "qy2XB/7z8CmbmY2LQ8ehOkAlw3fUW1f/FTIH9+2W5PlFYr1x9TUzOQFYmZTT91YmtFgp7i45dX5dsG7sU1C6CA=="
